Add provider equinix and module_name in Equinix Metal TF configs
equinix/terraform-metal-vsphere pull request #60
Opened 2023-05-08 20:06 UTC by vasubabu

2023-05-08 20:32 UTC, ctreatma requested changes

2023-05-08 20:32 UTC, ctreatma commented on .github/workflows/black.yml
> +        - 3.6.7 # Match the version on the gateway node
It looks like GitHub Actions doesn't know how to set up python 3.6.7 on ubuntu 22.04: https://github.com/equinix/terraform-metal-vsphere/actions/runs/4919295677/jobs/8786728960?pr=60#step:3:7

2023-05-09 03:54 UTC, displague commented on versions.tf
> +  #experiments = [module_variable_optional_attrs]
#57 addresses this

2023-05-16 20:51 UTC, ctreatma approved these changes

2023-05-16 20:51 UTC, merged